### ISSUE TITLE
Monitor task fails with no such file error

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#363]
Using Tekton 0.7 and the latest extension code I expect the monitor task to run to completion and upload results to the pull request.

The monitor task is seen to fail with:

```
<Response [201]>
Checking pipelinerun simple-pipeline-run-knsvx in namespace tekton-pipelines
Failed - pipelinerun simple-pipeline-run-knsvx in namespace tekton-pipelines
Traceback (most recent call last): 
 File "<stdin>", line 77, in <module>
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile    with open(src, 'rb') as fsrc:IOError: [Errno 2] No such file or directory: '/workspace/pull-request/comments/.MANIFEST'
```

We might need to add an if statement to protect against failing on older levels of Tekton perhaps something of the ilk:

```
if not os.path.exists("/workspace/output/pull-request/comments"):
        os.makedirs("/workspace/output/pull-request/comments")
        shutil.copyfile("/workspace/pull-request/comments/.MANIFEST","/workspace/output/pull-request/comments/.MANIFEST")
```

**Comment by dibbles** [comment]
https://github.com/tektoncd/experimental/pull/366

**Comment by a-roberts** [comment]
Merged so closing
