### ISSUE TITLE
Webhooks extension can Go panic handling events

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/experimental#487]
Found as part of https://github.com/tektoncd/experimental/issues/480, I'm using Triggers 0.3.1

# Expected Behavior
One should not Go panic.

# Actual Behavior
Plenty of Go panics seen when I did a push, with eleven active webhooks.

# Steps to Reproduce the Problem

1. I created eleven webhooks, TODO see if it's the case with one, count them Go panics
2. Push to your repository
3. Get the logs for the webhooks extension validator

# Additional Info
Things still worked (e.g. resources were created), but this is obviously not great

# Big logs

```
2020/03/10 09:46:26 [adam10-tekton-pipelines-pullrequest-event] Clone URL coming in as JSON: https://github.ibm.com/AROBERTS/devops-world-example.git
2020/03/10 09:46:26 [adam10-tekton-pipelines-pullrequest-event] Handling GitHub Event with delivery ID: ee94953a-62b3-11ea-83fa-cbecce2ddf54
2020/03/10 09:46:26 [adam10-tekton-pipelines-pullrequest-event] Validation FAIL (event type does not match, got push but wanted one of [pull_request, Merge Request Hook])
2020/03/10 09:46:26 [adam8-tekton-pipelines-push-event] Clone URL coming in as JSON: https://github.ibm.com/AROBERTS/devops-world-example.git
2020/03/10 09:46:26 [adam8-tekton-pipelines-push-event] Handling GitHub Event with delivery ID: ee94953a-62b3-11ea-83fa-cbecce2ddf54
2020/03/10 09:46:26 [adam8-tekton-pipelines-push-event] Validation PASS (repository URL, secret payload, event type checked)
2020/03/10 09:46:26 [adam5-tekton-pipelines-push-event] Clone URL coming in as JSON: https://github.ibm.com/AROBERTS/devops-world-example.git
2020/03/10 09:46:26 [adam5-tekton-pipelines-push-event] Handling GitHub Event with delivery ID: ee94953a-62b3-11ea-83fa-cbecce2ddf54
2020/03/10 09:46:26 [adam5-tekton-pipelines-push-event] Validation PASS (repository URL, secret payload, event type checked)
2020/03/10 09:46:26 http: panic serving 10.1.5.74:45204: runtime error: invalid memory address or nil pointer dereference
goroutine 764 [running]:
net/http.(*conn).serve.func1(0xc0007ce140)
	net/http/server.go:1767 +0x139
panic(0x1034960, 0x1bba870)
	runtime/panic.go:679 +0x1b2
main.addBranchAndTag(0x113cf20, 0xc000844000, 0x113cf20, 0xc000844000, 0xe, 0x0, 0x0)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/utils.go:119 +0x7aa
main.handlePush(0xc00026f000, 0x12faa00, 0xc0002682a0, 0xc0009503f0, 0x21, 0xc0006a6000, 0x1cad, 0x1e00, 0x0, 0xc000822780, ...)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/github.go:69 +0x387
main.HandleGitHub(0xc00026f000, 0x12faa00, 0xc0002682a0, 0xc0009503f0, 0x21, 0xc0009c83c0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/github.go:38 +0x2b7
main.main.func1(0x12faa00, 0xc0002682a0, 0xc00026f000)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/interceptor.go:86 +0xcce
net/http.HandlerFunc.ServeHTTP(0x11f58a8, 0x12faa00, 0xc0002682a0, 0xc00026f000)
	net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0x1bcd940, 0x12faa00, 0xc0002682a0, 0xc00026f000)
	net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0002681c0, 0x12faa00, 0xc0002682a0, 0xc00026f000)
	net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0007ce140, 0x12ff080, 0xc0008f45c0)
	net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	net/http/server.go:2928 +0x384
2020/03/10 09:46:26 http: panic serving 10.1.5.74:45398: runtime error: invalid memory address or nil pointer dereference
goroutine 899 [running]:
net/http.(*conn).serve.func1(0xc0007ce5a0)
	net/http/server.go:1767 +0x139
panic(0x1034960, 0x1bba870)
	runtime/panic.go:679 +0x1b2
main.addBranchAndTag(0x113cf20, 0xc0000d10e0, 0x113cf20, 0xc0000d10e0, 0xe, 0x0, 0x0)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/utils.go:119 +0x7aa
main.handlePush(0xc000710100, 0x12faa00, 0xc0005dc380, 0xc0009193e0, 0x21, 0xc0008a8000, 0x1cad, 0x1e00, 0x0, 0xc000a31400, ...)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/github.go:69 +0x387
main.HandleGitHub(0xc000710100, 0x12faa00, 0xc0005dc380, 0xc0009193e0, 0x21, 0xc00081b540, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/github.go:38 +0x2b7
main.main.func1(0x12faa00, 0xc0005dc380, 0xc000710100)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/interceptor.go:86 +0xcce
net/http.HandlerFunc.ServeHTTP(0x11f58a8, 0x12faa00, 0xc0005dc380, 0xc000710100)
	net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0x1bcd940, 0x12faa00, 0xc0005dc380, 0xc000710100)
	net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0002681c0, 0x12faa00, 0xc0005dc380, 0xc000710100)
	net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0007ce5a0, 0x12ff080, 0xc0008f44c0)
	net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	net/http/server.go:2928 +0x384
```

What's at those line numbers?

`main.addBranchAndTag(0x113cf20, 0xc000844000, 0x113cf20, 0xc000844000, 0xe, 0x0, 0x0)`

github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/utils.go:119 ->

`WebhookSuggestedImageTag: getSuggestedTag(event.GetRef(), *event.HeadCommit.ID)`

github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/github.go:69 ->

`returnPayload, err := addBranchAndTag(hookPayload)`

github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/github.go:38 ->

```
case event == "push":
  return handlePush(request, writer, foundTriggerName, payload) <-- this
```

github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/interceptor.go:86 ->

`returnPayload, err = HandleGitHub(request, writer, foundTriggerName, foundSecret)`

**Comment by a-roberts** [comment]
I'll have a look, so this is with push events on GHE in my test scenario, we should look at GitLab too.

```
func getSuggestedTag(ref, commit string) string {
	var suggestedImageTag string
	if strings.HasPrefix(ref, "refs/tags/") {
		suggestedImageTag = ref[strings.LastIndex(ref, "/")+1:]
	} else {
		suggestedImageTag = commit[0:7]
	}
	return suggestedImageTag
}
```

my first place to look (note the strigns.LastIndex call

**Comment by a-roberts** [comment]
Really can't reproduce this, done so many pushes, branch creations, PRs, and unsupported events (so curling my EL for example). Will work on other bugs but curious if anyone else sees this (leaving open at least for now)

**Comment by a-roberts** [comment]
Still unable to reproduce this so if you do see it and have a reproduce let's reopen this and address there (if it's specific to the extension), otherwise we should raise it against Triggers if we know the issue's there for sure.
